# -*- coding: utf-8 -*-
"""Day 6 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-PCwGwqZjv18vffCRSXvhhbeiy8n39N5

**Assignment 1 Day 6**
"""

class bank():
  def __init__(self,ownerName,balance):
    self.ownername = ownerName
    self.balance = balance
  
  def deposite(self,amount):
    self.balance += amount
    print("Your Updated Balance is : ", self.balance)
  
  def withdraw(self,amount):
    if (self.balance>amount):
      self.balance -= amount
      print("Your Updated Balance is : ", self.balance)
    else:
      print("You don't have enough Balance in you Accounr, Your Available Amount is : ", self.balance)

vishal = bank("Vishal",50000)

vishal.deposite(20000)

vishal.withdraw(45000)

vishal.withdraw(30000)

viki = bank("Viki",45000)

viki.withdraw(40000)

viki.deposite(30000)

viki.withdraw(40000)

"""**Assignment 2 Day 6**"""

import math

class cone():
  def __init__ (self,radius,height):
    self.radius = radius
    self.height = height

  def volume(self):
    vol = math.pi * self.radius**2 * (self.height/3)
    print("Volume of Cone is : ", vol)
  
  def surfacearea(self):
    sabase = math.pi * self.radius**2
    saside = math.pi * self.radius * math.sqrt(self.radius**2 + self.height**2)
    print("Surface Area of Base of Cone is : ", sabase)
    print("Surface Area of Side of Cone is : ", saside)

con = cone(2,4)

con.volume()

con.surfacearea()

