# -*- coding: utf-8 -*-
"""Day 5 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14pZ0SiQwPPuwoNvPE3Dq4Lqsn8sIZa_S

**Assignment 1 Day 5**
"""

lst = [1,1,5]
lst1 = [1,5,6,4,1,2,3,5]
count = 0
r=0
for x in lst:
  for y in lst1[r:]:
    r=r+1
    if (x==y):
      count=count+1
      break;
    else:
      pass
if(count==3):
  print("it’s a Match")
else:
  print("it’s Gone")

lst2 = [1,5,6,5,1,2,3,6]
count = 0
r=0
for x in lst:
  for z in lst2[r:]:
    r=r+1
    if (x==z):
      count=count+1
      break;
    else:
      pass
if(count==3):
  print("it’s a Match")
else:
  print("it’s Gone")

"""**Assignment 2 Day 5**"""

def prime(num):
  for i in range(2, num):
    if (num%i) == 0:
      break
    else:
      return num
number = filter(prime,range(1,2500))
print(list(number))

"""**Assignment 3 Day 5**"""

lst = ["hey this is sai","i am in mumbai","...."]

lst_new = map(lambda a: a.title(), lst)

list(lst_new)

