# -*- coding: utf-8 -*-
"""Day 4 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jy6Tm5Khh3Z5t5nkiC7nqBlIy9ckR_zY
"""

for a in range(1042000, 702648265):
  l = len(str(a))
  s = 0
  t = a
  i=0
  while t > 0:
    d = t % 10
    s +=d**l
    t//=10
  if a == s:
    print(a)
    i = i + 1
    if i==1:
      break

